server:
  port: 9092
spring:
  application:
    name: temp
  redis:
    host: 120.79.166.245 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: "123456" # Redis服务器连接密码（默认为空，以及这里带引号！！！）
    timeout: 3000ms # 连接超时时间（毫秒）